# Generated by Django 3.0.3 on 2020-02-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Media')),
                ('features', models.CharField(max_length=200)),
                ('prices', models.IntegerField()),
            ],
        ),
    ]
